name: Sync repository with apache/infrastructure-agenda

on:
  schedule:
    - cron: '0 0 * * *'

# https://stackoverflow.com/a/61574295/836177
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Sam Ruby'
          git config --global user.email 'rubys@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/apache/infrastructure-agenda.git
          git fetch upstream
          git merge --no-edit upstream/master
          git push origin master

